### ISSUE TITLE
Add Checklist Tool Support

### ISSUE THREAD

**Issue by alaminfirdows** [alaminfirdows/laravel-editorjs#14]
We need to add the support to render the Checklist. This tool allows users to easily create checklists within their text, providing an essential feature for better content organization.

Please refer to the official repository for the Checklist Tool here: [Editor.js Checklist Tool](https://github.com/editor-js/checklist).

Reference: https://github.com/editor-js/checklist

**Comment by lmottasin** [comment]
@alaminfirdows vai working on this 🔨
