### ISSUE TITLE
How to create a new post?

### ISSUE THREAD

**Issue by Reegan01** [alaminfirdows/laravel-editorjs#3]
Can you please elaborate how to create a new page with editor?

**Comment by alaminfirdows** [comment]
Hello @Reegan01 ,

It's just a parser for PHP/Laravel. You can render your editpr.js json data to markup languages.

If you want to edit a page, store the json data to your Model's body fields then render it by this package.

Example:

```php
use App\Models\Page;

$page = Page::find(1);
echo LaravelEditorJs::render($page->body);
```

You can make an accessor also.

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use AlAminFirdows\LaravelEditorJs\Facades\LaravelEditorJs;

class Page extends Model
{
    public function getBodyAttribute()
    {
        return LaravelEditorJs::render($this->attributes['body']);
    }
}

$page = Page::find(1);
echo $page->body;
```
