### ISSUE TITLE
Upgrade 

### ISSUE THREAD

**Issue by valsha** [alaminfirdows/laravel-editorjs#6]
Hi, maybe there is a better way to use the new 

https://github.com/codex-team/editor.js/releases/tag/v2.28.0

or change 

```
require": {		
		"codex-team/editor.js": "v2.0.7",
```
to
` "codex-team/editor.js": "*",`

Thank you.

**Comment by alaminfirdows** [comment]
I haven't noticed any updates in the [editorjs-php](https://github.com/editor-js/editorjs-php) repository. The latest release of Editor.js seems to be focused on improvements to the client-side editor.

So, as of now, it doesn't appear that we have any updates to make on our end.
